/*This Script is generated by Jogi Prasad Pakki
No one allowed to use or modify this script.
If you any questions mail me to jogiprasadpakki@gmail.com 
Copy right 2018 All reserved by Jogi Prasad Pakki */

using System;
using UnityEngine;

namespace AndroidNativeCore
{
    public class AndroidCore {

        public const string PluginPackage = "com.jogiprasadpakki.unity.androidnativecore";
        private const string currentPackage = PluginPackage + ".Core";

        private static AndroidJavaObject AndroidUri(string data)
        {     
            AndroidJavaClass uri = new AndroidJavaClass("android.net.Uri");
            AndroidJavaObject Uri = uri.CallStatic<AndroidJavaObject>("parse", data);
            return Uri;
        }

        public static AndroidJavaObject getActivity()
        {
            AndroidJavaClass unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
            AndroidJavaObject activity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");
            return activity;
        }
        public static AndroidJavaObject getContext()
        {
            AndroidJavaClass unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
            AndroidJavaObject activity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");
            AndroidJavaObject context = activity.Call<AndroidJavaObject>("getApplicationContext");
            return context;
        }

        public static void makeCall(string number)
        {
            AndroidJavaObject intentO = new AndroidJavaObject("android.content.Intent");
            intentO.Call<AndroidJavaObject>("setAction", "android.intent.action.CALL");
            intentO.Call<AndroidJavaObject>("setData",AndroidUri("tel:" + number));
            getActivity().Call("startActivity", intentO);
        }
        public static void dial(string number)
        {
            AndroidJavaObject intentO = new AndroidJavaObject("android.content.Intent");
            intentO.Call<AndroidJavaObject>("setAction", "android.intent.action.DIAL");
            intentO.Call<AndroidJavaObject>("setData",AndroidUri("tel:" + number));
            getActivity().Call("startActivity", intentO);      
    
        }
        public static void composeMessage(string number,string message)
        {
            AndroidJavaObject intentO = new AndroidJavaObject("android.content.Intent", "android.intent.action.VIEW", AndroidUri("sms:" + number));
            intentO.Call<AndroidJavaObject>("putExtra", "sms_body", message);
            getActivity().Call("startActivity", intentO);
        }
        public static void composeMail(string emailAddress,string subject,string body) 
        {
            AndroidJavaObject intentO = new AndroidJavaObject("android.content.Intent", "android.intent.action.SENDTO", AndroidUri("mailto:" + emailAddress));
            intentO.Call<AndroidJavaObject>("putExtra", "android.intent.extra.SUBJECT", subject);
            intentO.Call<AndroidJavaObject>("putExtra", "android.intent.extra.TEXT", body);
            getActivity().Call("startActivity", intentO);
        }


        public static void share(string extraSubject,string extraText)
        {
            AndroidJavaObject intentO = new AndroidJavaObject("android.content.Intent");
            intentO.Call<AndroidJavaObject>("setAction","android.intent.action.SEND");
            intentO.Call<AndroidJavaObject>("setType", "text/plain");
            intentO.Call<AndroidJavaObject>("putExtra", "android.intent.extra.SUBJECT", extraSubject);
            intentO.Call<AndroidJavaObject>("putExtra", "android.intent.extra.TEXT",extraText);
            getActivity().Call("startActivity", intentO);
        }
        public static void share(string extraText,Texture2D extraStream)
        {
            DateTime d = DateTime.Now;
            string timestamp =  d.ToString("yyyyMMddHHmmssfff");     
            AndroidJavaObject a = new AndroidJavaObject(AndroidCore.PluginPackage + ".Core");
            string img_uri = insertImage(extraStream, Application.productName+timestamp+".png", null);
            AndroidJavaObject intentO = new AndroidJavaObject("android.content.Intent");
            intentO.Call<AndroidJavaObject>("setAction", "android.intent.action.SEND");
            intentO.Call<AndroidJavaObject>("setType", "image/*");
            intentO.Call<AndroidJavaObject>("putExtra", "android.intent.extra.TEXT", extraText);
            intentO.Call<AndroidJavaObject>("putExtra", "android.intent.extra.STREAM", AndroidUri(img_uri));
            getActivity().Call("startActivity", intentO);

        }
        public static string insertImage(Texture2D texture2D,string title,string description)
        {
            byte[] img_data = texture2D.EncodeToPNG();
            AndroidJavaObject obj = new AndroidJavaObject(AndroidCore.PluginPackage + ".Core");
            return obj.Call<string>("saveBitmap", img_data, title,description);
        }
       
        public static bool isApplicationInstalled(string package)
        {
            AndroidJavaObject obj = new AndroidJavaObject(AndroidCore.PluginPackage + ".Core");
            return obj.Call<bool>("isApplicationInstalled",package);
        }
        public static void openApplication(string package)
        {
            AndroidJavaObject obj = new AndroidJavaObject(AndroidCore.PluginPackage + ".Core");
            obj.Call("LunchApp",package);
        }
        public static void openApplicationView(string data)
        {
            AndroidJavaObject intentO = new AndroidJavaObject("android.content.Intent");
            intentO.Call<AndroidJavaObject>("setAction", "android.intent.action.VIEW");
            intentO.Call<AndroidJavaObject>("setData",AndroidUri(data));
            getActivity().Call("startActivity", intentO);
        }
    }
}