/*This Script is generated by Jogi Prasad Pakki
No one allowed to use or modify this script.
If you any questions mail me to jogiprasadpakki@gmail.com 
Copy right 2018 All reserved by Jogi Prasad Pakki */

using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace AndroidNativeCore
{
    public class NotificationManager{

        public const int PRIORITY_DEFAULT = 0x00000000;
        public const int PRIORITY_HIGH = 0x00000001;
        public const uint PRIORITY_LOW = 0xffffffff;
        public const int PRIORITY_MAX = 0x00000002;
        public const uint PRIORITY_MIN = 0xfffffffe;

        public const int IMPORTANCE_DEFAULT = 0x00000003;
        public const int IMPORTANCE_HIGH = 0x00000004;
        public const int IMPORTANCE_LOW = 0x00000002;
        public const int IMPORTANCE_MAX = 0x00000005;
        public const int IMPORTANCE_MIN = 0x00000001;
        public const int IMPORTANCE_NONE = 0x00000000;

        public const int VISIBILITY_PRIVATE = 0x00000000;
        public const int VISIBILITY_PUBLIC = 0x00000001;
        public const uint VISIBILITY_SECRET = 0xffffffff;     


        private AndroidJavaObject obj;

        public NotificationManager()
        {
            obj = new AndroidJavaObject(AndroidCore.PluginPackage + ".NotificationManager");
        }
        public void createChannel(Channel channel)
        {
            obj.Call("channel", channel.id, channel.name, channel.description, channel.importance,channel.lockScreenVisibility,channel.enableLights,channel.lightColor,channel.enableVibration,channel.enableBadge,channel.vibrationPattren);
        }
        public void deleteChannel(string id)
        {
            obj.Call("deleteNotificationChanel", id);
        }

        public class Channel
        {                           
            public int importance = IMPORTANCE_DEFAULT;
            public string id,name,description;
            public string lightColor = "#ffff";
            public int lockScreenVisibility = VISIBILITY_PRIVATE;
            public bool enableLights,enableVibration,enableBadge = false;
            public long[] vibrationPattren;
               
                //notifi.Call("crateNotificationChanel", id, name, description, importence, lockScreenVisibility, enableLights, lightColor, enableVibration, enableBadge);
            
        }

        public class Builder
        {
            private string img_url = "null";
            private AndroidJavaObject obj;

            public Builder Create(NotificationManager notificationManager,string chanel)
            {
                obj = notificationManager.obj;
                obj.Call("NotificationBuilder", chanel);
                return this;
            }
            public Builder setIcon(string resourseName)
            {
                obj.Call("NotificationSetIcon", resourseName);
                return this;
            }
            public Builder setDefautlSound()
            {
                obj.Call("NotificationSetDefaultSound");
                return this;
            }
            public Builder setContentTitle(string title)
            {
                obj.Call("NotificationSetTitle", title);
                return this;
            }
            public Builder setBigText(string text)
            {
                obj.Call("NotificationSetMsg", text);
                return this;
            }
            public Builder setContentText(string text)
            {
                obj.Call("NotificationBigMsg", text);

                return this;

            }
            public Builder setBigImage(Texture2D largeicon)
            {
                byte[] data = largeicon.EncodeToPNG();
                obj.Call("NotificationSetLargeIcon", data);
                return this;
            }
            public Builder setBigImage(string url)
            {
                this.img_url = url;
                return this;
            }
            public Builder setSound(string resourceId)
            {
                obj.Call("NotificationSetSound", resourceId);
                return this;
            }
            public Builder setPriority(int priority)
            {
                obj.Call("NotificationSetPriority", priority);
                return this;
            }
            public Builder setGroup(string groupName, bool showGroupSummery)
            {
                obj.Call("NotificationsetGroup", groupName, showGroupSummery);
                return this;
            }
            public Builder setAutoCansel(bool autoCansel)
            {
                obj.Call("NotificationAutoCansel", autoCansel);
                return this;
            }
            public void notify(int id)
            {
                obj.Call("ShowNotification", id, img_url);
            }
        }
    }
}
 



